create table if not exists public.products (
  sku text primary key,
  name text not null,
  unit text not null default 'vial',
  price_mxn integer not null check (price_mxn >= 0),
  source_price_mxn integer check (source_price_mxn >= 0),
  stock_on_hand integer not null default 0 check (stock_on_hand >= 0),
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  active boolean not null default true,
  source text not null default 'airtable-import',
  updated_at timestamptz not null default now()
);
create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  sku text not null references public.products(sku),
  quantity_delta integer not null check (quantity_delta <> 0),
  movement_type text not null check (movement_type in ('initial_import', 'restock', 'sale', 'refund', 'adjustment')),
  order_id bigint references public.orders(id),
  mp_payment_id text,
  note text,
  created_at timestamptz not null default now(),
  unique (order_id, sku, movement_type)
);
alter table public.products enable row level security;
alter table public.inventory_movements enable row level security;
revoke all on public.products from anon, authenticated;
revoke all on public.inventory_movements from anon, authenticated;
grant all on public.products to service_role;
grant all on public.inventory_movements to service_role;
alter table public.orders add column if not exists external_reference text;
create unique index if not exists orders_external_reference_key
  on public.orders (external_reference)
  where external_reference is not null;
insert into public.products
  (sku, name, price_mxn, source_price_mxn, stock_on_hand, active)
values
  ('bact-water-10', 'Agua Bacteriostática 10ml', 0, 1200, 85, false),
  ('bact-water-3', 'Agua Bacteriostática 3ml', 300, 1200, 126, true),
  ('bact-water-30', 'Agua Bacteriostática 30ml', 900, null, 0, false),
  ('bpc-tb500-10', 'BPC-157/TB-500 10mg/10mg', 4900, 950, 15, true),
  ('bpc-tb500', 'BPC-157/TB-500 5mg/5mg', 3700, 650, 19, true),
  ('cjc-1295', 'CJC-1295/Ipamorelin 5mg/5mg', 3900, 2800, 22, true),
  ('dsip-10', 'DSIP 10mg', 3700, 3200, 24, true),
  ('epitalon', 'Epitalon 10mg', 3400, 3400, 15, true),
  ('ghk-cu-100', 'GHK-Cu 100mg', 3700, 6500, 5, true),
  ('ghk-cu-50', 'GHK-Cu 50mg', 3400, null, 10, true),
  ('glow-70', 'GLOW Protocol', 4900, 4900, 46, true),
  ('glp3-12', 'GLP-3 12mg', 3900, 3900, 69, true),
  ('glp3-24', 'GLP-3 24mg', 5400, 5400, 50, true),
  ('glp3-48', 'GLP-3 48mg', 7400, 7400, 0, true),
  ('igf1-lr3-100', 'IGF-1 LR3 100mg', 0, null, 0, false),
  ('kisspeptin-10', 'Kisspeptin 10mg', 3400, null, 11, true),
  ('motsc-10', 'MOTS-C 10mg', 3900, 2400, 13, true),
  ('nad-buffered', 'NAD+ Buffered', 4100, null, 0, true),
  ('pt141', 'PT-141 10mg', 3400, 3400, 16, true),
  ('semax-10', 'Semax / Selank', 3700, null, 0, true),
  ('tesa-ipa', 'Tesamorelin / Ipamorelin', 4400, 4400, 19, true)
on conflict (sku) do update set
  name = excluded.name,
  price_mxn = excluded.price_mxn,
  source_price_mxn = excluded.source_price_mxn,
  stock_on_hand = excluded.stock_on_hand,
  active = excluded.active,
  updated_at = now();
insert into public.inventory_movements (sku, quantity_delta, movement_type, note)
select sku, stock_on_hand, 'initial_import', 'Imported from Airtable on 2026-07-27'
from public.products
where stock_on_hand > 0
on conflict do nothing;
create or replace function public.apply_paid_order_inventory(
  p_order_id bigint,
  p_payment_id text
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  item jsonb;
  current_stock integer;
  requested_qty integer;
  item_sku text;
begin
  if exists (
    select 1 from public.orders
    where id = p_order_id and mp_payment_id = p_payment_id and status = 'approved'
  ) then
    return jsonb_build_object('ok', true, 'duplicate', true);
  end if;

  for item in
    select value from jsonb_array_elements(
      (select products from public.orders where id = p_order_id for update)
    )
  loop
    item_sku := item->>'sku';
    requested_qty := greatest(1, (item->>'qty')::integer);

    select stock_on_hand into current_stock
    from public.products
    where sku = item_sku
    for update;

    if current_stock is null then
      raise exception 'Unknown inventory SKU: %', item_sku;
    end if;
    if current_stock < requested_qty then
      raise exception 'Insufficient stock for %: have %, need %', item_sku, current_stock, requested_qty;
    end if;

    update public.products
    set stock_on_hand = stock_on_hand - requested_qty, updated_at = now()
    where sku = item_sku;

    insert into public.inventory_movements
      (sku, quantity_delta, movement_type, order_id, mp_payment_id, note)
    values
      (item_sku, -requested_qty, 'sale', p_order_id, p_payment_id, 'Mercado Pago approved');
  end loop;

  update public.orders
  set status = 'approved', mp_payment_id = p_payment_id
  where id = p_order_id;

  return jsonb_build_object('ok', true, 'duplicate', false);
end;
$$;
revoke all on function public.apply_paid_order_inventory(bigint, text) from public, anon, authenticated;
grant execute on function public.apply_paid_order_inventory(bigint, text) to service_role;
